# Generated by Django 4.2.7 on 2024-12-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("refresh_token", models.TextField(null=True)),
                ("access_token", models.TextField(null=True)),
            ],
        ),
    ]
